### PR TITLE
[READY] Add js es6 support

### PR DESCRIPTION
**Pull request by NathanGASC**
This pull request has for purpose to add es6 support to BBbuilder.

### CODE REVIEW

**Comment by Enduriel** [comment]
Personally I think it'd be cleaner to have something like a ui_es6/ui_modern folder that would instead transpile into the ui folder, rather than having an additional parameter, it'd also make it easier to update parts of a mod at a time without breaking anything.

**Comment by NathanGASC** [comment]
I want to have something which is invisible for the dev. I don't want him to ask himself "Am I in es3 or es6 ? Do I work in the right folder ? What is the difference between es6 and es3 ? ...". 

Also there is no incompatibility between es6 and es3. Both can be in the same folder and be transpiled. Es3 code will probably stay the same, when es6 will change drastically. So if you want to update a mod, you can always in your mod have two folders to sort old js/new js without making it mandatory for everyone. Plus I bet everyone will use the modern js syntax because there is no more reason to use old version :D.

For the additional flag, if there is too much of them it will probably better to have something like babel. To avoid using command line with X parameters, they handle a config file named babel.config.json that you can find in this branch. It's used to configure babel and you just give the json path in the cli. We can have something like bbbuilder_config.json to configure bbbuilder.

Still there is a plus to use old js. There is no transpilation so build time are shorter. Also there is no polyfills so it will improve performance. From my test, when I include ALL polyfills, I go from 95fps to 15fps. So if all the mods you have installed use too much polyfills it will decrease performances. It's something to test, I don't know if the issue is about certain polyfills or the accumulation of them.

**Comment by Enduriel** [comment]
It might be worth it to do some more testing on Polyfills and their performance implications, also from what I understand babel only includes polyfills as necessary for the target build? Once of the things I also mentioned to Taro would be to make sure you're only targeting chrome v48, as that is what BB is running with (with some features excluded but those are not polyfillable) to minimize the amount of excess polyfills that are included in builds.

**Comment by NathanGASC** [comment]
Yes, Babel include only necessary polyfills for the current mod. So basically multiple mod will maybe write the same polyfill. Which is pretty normal as they must be standalone in general.

**Comment by NathanGASC** [comment]
After this commit we reach almost 5s of compilation time when dependencies are installed :/ . Probably due to the way I check dependencies (When I do "npm -g list" in my cmd, it take almost 1s to display the list. Can always use "--version" foreach modules to check instead as it's faster).

**Comment by NathanGASC** [comment]
It's ready to be merge on my side. Don't hesitate to give me feedbacks 👍

**Comment by NathanGASC** [comment]
continue at https://github.com/TaroEld/BBbuilder/pull/5

**Pull request closed without merging**
